version: '3.3'

# You must have a file .env at the root of the project with this value:
# MYSQL_PASSWORD=
# MYSQL_ROOT_PASSWORD=
# EMAIL_PASSWORD=
# EMAIL_USER=
# EMAIL_PROVIDER=

volumes:
  images:

services:
  reverseproxy:
    build: ./services/reverseproxy/
    ports:
      - 8080:8080
    restart: always

  nginx:
    depends_on:
      - reverseproxy
    build: ./services/nginx/
    links:
      - php
    volumes:
      - ./app/:/var/www/html/
      - images:/srv/images/
    restart: always

  php:
    build:
      context: ./services/php/
      args:
        EMAIL_PASSWORD: ${EMAIL_PASSWORD}
        EMAIL_USER: ${EMAIL_USER}
        EMAIL_PROVIDER: ${EMAIL_PROVIDER}
    expose:
      - 9000
    links:
      - db
    volumes:
      - ./app/:/var/www/html/
      - images:/srv/images/
    environment:
      DATABASE_NAME: db
      DATABASE_USER: user
      DATABASE_PASS: ${MYSQL_PASSWORD}
      FROM_EMAIL: ${EMAIL_USER}@${EMAIL_PROVIDER}
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8081:80
    restart: always

  db:
    build: ./services/db/
    container_name: db
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
